# Generated by Django 4.2.4 on 2023-09-07 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='koder',
            name='address',
            field=models.CharField(default=datetime.datetime(2023, 9, 7, 0, 44, 11, 770670, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='koder',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='koder',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('finished', 'Finished')], default='activo', max_length=8),
        ),
    ]
